name: Github release

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/json-patch-validator.jar
            target/json-patch-validator-javadoc.jar
            target/json-patch-validator-sources.jar